// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO8osHpimnM5suKWdwgmftBTfqOOkD0Vo',
    appId: '1:869322838623:web:b6a8dd2f2c3b54a7d881ea',
    messagingSenderId: '869322838623',
    projectId: 'kairos-a5e9b',
    authDomain: 'kairos-a5e9b.firebaseapp.com',
    storageBucket: 'kairos-a5e9b.appspot.com',
    measurementId: 'G-2SLCRCXS4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAojxd-3ehD8xejvVnuIgLTeM8oneP9E-w',
    appId: '1:869322838623:android:ac29d79d058590eed881ea',
    messagingSenderId: '869322838623',
    projectId: 'kairos-a5e9b',
    storageBucket: 'kairos-a5e9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOtdQJaF1cRaGW1GPGPVvSZAuYTHXVbeA',
    appId: '1:869322838623:ios:b4913c908e9faca6d881ea',
    messagingSenderId: '869322838623',
    projectId: 'kairos-a5e9b',
    storageBucket: 'kairos-a5e9b.appspot.com',
    iosBundleId: 'com.example.kairos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOtdQJaF1cRaGW1GPGPVvSZAuYTHXVbeA',
    appId: '1:869322838623:ios:b4913c908e9faca6d881ea',
    messagingSenderId: '869322838623',
    projectId: 'kairos-a5e9b',
    storageBucket: 'kairos-a5e9b.appspot.com',
    iosBundleId: 'com.example.kairos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO8osHpimnM5suKWdwgmftBTfqOOkD0Vo',
    appId: '1:869322838623:web:9c5ef715afbf6ff9d881ea',
    messagingSenderId: '869322838623',
    projectId: 'kairos-a5e9b',
    authDomain: 'kairos-a5e9b.firebaseapp.com',
    storageBucket: 'kairos-a5e9b.appspot.com',
    measurementId: 'G-0GB19QEX39',
  );
}
